[project]
name = "agio-desk"
version = "0.0.6"
requires-python = ">=3.10"
dependencies = [
    "psutil>=7.0.0",
    "pyside6>=6.9.1",
]
license = "MIT"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"agio_desk" = [
    "__agio__.yml",
]